version: '3.6'
services:
  dapp:
    image: ${CONTAINER_IMAGE}
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      placement:
        constraints:
          - node.labels.${ENVIRONMENT} == true
      mode: replicated
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME}-dapp-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME}-dapp-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${STACK_NAME}-dapp-http.service=${STACK_NAME}-dapp
        - traefik.http.routers.${STACK_NAME}-dapp-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME}-dapp.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-dapp.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${STACK_NAME}-dapp.service=${STACK_NAME}-dapp
        - traefik.http.routers.${STACK_NAME}-dapp.tls=true
        - traefik.http.routers.${STACK_NAME}-dapp.tls.certresolver=le
        - traefik.http.services.${STACK_NAME}-dapp.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
