image: $BASE_CI_IMAGE
services:
  - $BASE_CI_SERVICE_IMAGE

stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  BASE_IMAGE: $CI_REGISTRY_IMAGE:base
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $USER -p $TOKEN $CI_REGISTRY
  - docker login -u $DOCKER_USER -p $DOCKER_TOKEN

build-dev:
  stage: build
  retry: 2
  script:
    - ENVIRONMENT=dev sh ./client/scripts/build-push.sh
  only:
    - develop

build-stage:
  stage: build
  retry: 2
  script:
    - ENVIRONMENT=stage sh ./client/scripts/build-push.sh
  only:
    - master

build-prod:
  stage: build
  retry: 2
  script:
    - ENVIRONMENT=prod sh ./client/scripts/build-push.sh
  only:
    - release

deploy-dev:
  stage: deploy
  retry: 2
  script:
    - >
      ENVIRONMENT=dev
      DOMAIN=d.saydapp.company
      STACK_NAME=say-dev-dapp
      sh ./client/scripts/deploy.sh
  only:
    - develop
  tags:
    - deploy

deploy-stage:
  stage: deploy
  retry: 2
  script:
    - >
      ENVIRONMENT=stage 
      DOMAIN=s.saydapp.company
      STACK_NAME=say-stage-dapp
      sh ./client/scripts/deploy.sh
  only:
    - master
  tags:
    - deploy

deploy-prod:
  stage: deploy
  retry: 2
  script:
    - >
      ENVIRONMENT=prod
      DOMAIN=saydapp.company
      STACK_NAME=say-dapp
      sh ./client/scripts/deploy.sh
  only:
    - release
  tags:
    - deploy-prod
